import type { NextPage } from "next";
import Head from "next/head";
import { ThreeDemo } from "../components/ThreeDemo/ThreeDemo";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThreeDemo />
      </main>
    </div>
  );
};

export default Home;
